GET http://localhost:9000/classes/65e0ac2b5ab4fe07178f0bbb

###
POST http://localhost:9000/classes/65f3c78ec471a5170d749f80
Content-type: application/json

{
    "note": "api test class",
    "paid": false
}

###

PUT http://localhost:9000/classes/65f33c1295953d0e7a3e8334
Content-Type: application/json

{
    "paid": true
}

###