POST http://localhost:9000/courses/65f3cdff6013a2fa62a2ea65
Content-Type: application/json

{
    "name": "chinese 1",
    "courseLength": 10
}

###

DELETE http://localhost:9000/courses/65f3c78ec471a5170d749f80

###